version: '3.8'

services:
  # Local PostgreSQL for development (optional - use when not using Supabase)
  postgres:
    image: postgres:15-alpine
    container_name: zamanyonet_postgres
    restart: always
    environment:
      POSTGRES_DB: randevu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/supabase_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - zamanyonet_network

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zamanyonet_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zamanyonet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - zamanyonet_network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: zamanyonet_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - zamanyonet_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  zamanyonet_network:
    driver: bridge 