version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: zamanyonet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: randevu_db
      MYSQL_USER: randevu_user
      MYSQL_PASSWORD: randevu_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - zamanyonet_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: zamanyonet_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - zamanyonet_network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: zamanyonet_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zamanyonet_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  zamanyonet_network:
    driver: bridge 