name: appointment_app
description: "Modern randevu sistemi uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & UX
  cupertino_icons: ^1.0.2
  
  # Takvim & Tarih
  table_calendar: ^3.0.9
  intl: ^0.20.2
  
  # Backend & Veritabanı
  mysql1: ^0.20.0
  uuid: ^4.0.0
  http: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Routing
  go_router: ^13.2.0
  
  # Local Storage
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/ 