name: appointment_app
description: "Modern randevu sistemi uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & UX
  cupertino_icons: ^1.0.2
  
  # Takvim & Tarih
  table_calendar: ^3.0.9
  intl: ^0.20.2
  
  # Backend & Veritabanı
  mysql1: ^0.20.0
  uuid: ^4.0.0
  http: ^1.1.0
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.1
  crypto: ^3.0.3
  
  # State Management
  provider: ^6.0.5
  
  # Routing
  go_router: ^13.2.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Charts & Analytics
  fl_chart: ^0.66.2
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Password Reset
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/zamanyonet_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/zamanyonet_logo.png"
    background_color: "#1976D2"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/images/zamanyonet_logo.png"
    icon_size: 48

flutter_native_splash:
  color: "#1976D2"
  image: assets/images/zamanyonet_logo.png
  branding: assets/images/zamanyonet_logo.png
  color_dark: "#0D47A1"
  image_dark: assets/images/zamanyonet_logo.png
  branding_dark: assets/images/zamanyonet_logo.png

  android_12:
    image: assets/images/zamanyonet_logo.png
    icon_background_color: "#1976D2"
    image_dark: assets/images/zamanyonet_logo.png
    icon_background_color_dark: "#0D47A1"

  web: false 